version: '3.4'

x-common-volumes:
  &common-volumes
  volumes:
    - .:${APP_DIR}/

services:
  app:
    ports:
      - ${DEFAULT_APP_PORT}:${DEFAULT_APP_PORT}
    <<: *common-volumes

  database:
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
