version: '3.4'

x-common-volumes:
  &common-volumes
  volumes:
    - .:${APP_DIR}/
    - node_modules:${APP_DIR}/node_modules

services:
  app:
    ports:
      - ${DEFAULT_APP_PORT}:${DEFAULT_APP_PORT}
    <<: *common-volumes

volumes:
  node_modules:
