version: '3.4'

# using extension fields is overkill in this scenario,
# but it can be useful if you need multiple similar
# instances of the same service
x-app-base:
  &app-base
  build:
    context: .
    args:
      - APP_DIR=${APP_DIR}
  command:
    - scripts/start_app.sh
  env_file:
    - docker/app.env
    - database/.env
  environment:
    - DEFAULT_APP_PORT=${DEFAULT_APP_PORT}
  ports:
    - ${DEFAULT_APP_PORT}
  volumes:
    - node_modules:${APP_DIR}/node_modules

x-database-base:
  &database-base
  image: postgres:9.4
  env_file:
    - database/.env
  environment:
    - DATABASE_PORT=${DATABASE_PORT}
  ports:
    - ${DATABASE_PORT}
  volumes:
    - data:/var/lib/postgresql/data

services:
  app:
    <<: *app-base
  database:
    <<: *database-base

volumes:
  node_modules:
  data:

